name: Build using poetry
on:
  push:
    branches:
      - "master"
jobs:
  build-application-actions:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run: sudo apt update && apt upgrade
      - run: sudo apt install curl
      - run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Poetry process
        run: |
          poetry install
          poetry build
      - run: echo "🍏 This job's status is ${{ job.status }}."
