name: Build using poetry
on:
  push:
    branches:
      - "master"
jobs:
  build-application-actions:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          sudo apt-get update 
          sudo apt-get upgrade
          apt-get install curl
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          export PATH=$PATH:/root/.poetry/bin
          poetry install
          poetry build
          echo "🍏 This job's status is ${{ job.status }}."
